### ISSUE TITLE
Whitelist IP untuk callback

### ISSUE THREAD

**Issue by hrace009** [ipaymu/ipaymu-php-api#12]
Dear Tim IpayMu,

Beberapa hari yang lalu saya menemukan celah di callback API saya. 
Dimana saya bisa melakukan transaksi **sukses** tanpa harus melakukan pembayaran dengan menggunakan postman.
hal tersebut terjadi karena tidak ada nya list IP Address server Ipaymu di callback API saya.
Mohon informasi list IP Address server iPaymu untuk saya whitelist di website saya.

Beberapa hari yang lalu saya sudah kontak ke support iPaymu melalui tiketing, dan hanya di berikan IP 120.89.93.249.
Saya cek di log website saya, yang melakukan callback bukan dari ip tersebut, melainkan dari IP server iPaymu yang lain.

Mohon di bantu untuk memberikan list ip yang lengkap supaya bisa saya whitelist dan bisa mengaman kan API callback saya.

Terima Kasih

**Comment by putuedi** [comment]
halo, untuk saat ini callback kami emang betul dari IP 120.89.93.249 dan tidak ada dari IP yang lain.
Jika ada perubahan IP kami pasti akan menginformasikan.

**Comment by hrace009** [comment]
> halo, untuk saat ini callback kami emang betul dari IP 120.89.93.249 dan tidak ada dari IP yang lain.
> Jika ada perubahan IP kami pasti akan menginformasikan.

Terima kasih atas informasi nya
