### ISSUE TITLE
Tidak Bisa Menambahkan Lebih Dari 1 Produk

### ISSUE THREAD

**Issue by nusagates** [ipaymu/ipaymu-php-api#6]
Saya menambahkan multiple produk kok selalu dapat error seperti berikut, ya:
`{"Status":400,"Message":"invalid request","Error":{"price.0":["The price.0 must be a number."]}}`

Ini kodingan saya untuk menambahakn produk:
`  $ipaymu->addCart(
            [
                'product'       =>[ 'Prod 1', "Prod 2"],
                'qty'           => [1, 1],
                'price'         => [1000, 5000],
                'description'   => ["Des1", "Des2"]
            ]
        );`

**Comment by MuhamadAhmadin** [comment]
Saya mengalami hal yang sama, mohon segera di tindak lanjuti tim dev

**Comment by putuedi** [comment]
> Saya menambahkan multiple produk kok selalu dapat error seperti berikut, ya: `{"Status":400,"Message":"invalid request","Error":{"price.0":["The price.0 must be a number."]}}`
> 
> Ini kodingan saya untuk menambahakn produk: ` $ipaymu->addCart( [ 'product' =>[ 'Prod 1', "Prod 2"], 'qty' => [1, 1], 'price' => [1000, 5000], 'description' => ["Des1", "Des2"] ] );`

halo, bisa dicoba update packagenya

**Comment by putuedi** [comment]
> Saya mengalami hal yang sama, mohon segera di tindak lanjuti tim dev

halo, bisa dicoba udpdate packagenya
