### ISSUE TITLE
Inconsistent JSON encoding causes 401 failure in requests

### ISSUE THREAD

**Issue by willnode** [ipaymu/ipaymu-php-api#8]
`json_encode` on here has inconsistent parameters applied so my requests are failing:

https://github.com/ipaymu/ipaymu-php-api/blob/ee61090e90248a44a24f93987a31156f9c4d84ad/iPaymu/Traits/CurlTrait.php#L24-L25

https://github.com/ipaymu/ipaymu-php-api/blob/ee61090e90248a44a24f93987a31156f9c4d84ad/iPaymu/Traits/CurlTrait.php#L55

**Comment by putuedi** [comment]
Hi, it's different function with different parameters. You can tell your problem to support@ipaymu.com. Thank you

**Comment by willnode** [comment]
Honestly, I did already ask for a support email a few weeks ago and I simply decided to handle CURL manually and no longer use this package. The 401 error case was unclear so maybe this one is the cause. thanks.
